import type { Exercise } from "../domain";
import { companySources, technicalSources } from "../sources";
import { defineCompanyExercises } from "../company-exercises/types";

/**
 * Shared drills that are especially relevant to Attio's flexible-data-model
 * and product-engineering interview themes. They intentionally omit
 * `companyId` so the company-world selector can reuse them for any relevant
 * company while the Attio module remains scoped to interview answers.
 */
export const attioFocusExercises: Exercise[] = [
  {
    id: "shared-attio-capability-vs-flag",
    skillId: "domain-modeling",
    track: "engineering",
    type: "choice",
    eyebrow: "Domain modeling",
    prompt: "An organization permanently supports a behavior, independent of rollout or experimentation. Which model best represents that fact?",
    instruction: "Choose the strongest domain model.",
    options: [
      { id: "capability", label: "An organization capability" },
      { id: "flag", label: "A feature flag that remains enabled" },
      { id: "preference", label: "A user preference" },
      { id: "loading", label: "A transient UI state" },
    ],
    correctOptionId: "capability",
    explanation: "A durable tenant-level fact is a capability. Flags are operational rollout controls and preferences belong to a user; conflating them makes lifecycle, ownership and authorization ambiguous.",
    tags: ["domain-modeling", "product-judgment"],
    source: technicalSources.domainModeling,
  },
  {
    id: "shared-attio-effective-config",
    skillId: "domain-modeling",
    track: "engineering",
    type: "multi-select",
    eyebrow: "Domain modeling",
    prompt: "You are designing organization defaults with subgroup overrides and user preferences. Which semantics must be explicit before implementation?",
    instruction: "Select every concern that defines a safe effective-value model.",
    options: [
      { id: "precedence", label: "Precedence between scopes" },
      { id: "absence", label: "What absence and explicit reset mean" },
      { id: "authority", label: "Who is allowed to override" },
      { id: "audit", label: "How changes are audited" },
      { id: "null", label: "Leave null meaning implicit" },
    ],
    correctOptionIds: ["precedence", "absence", "authority", "audit"],
    explanation: "Hierarchical configuration needs a documented precedence rule, default/reset semantics, authorization and change behavior. An overloaded null is a modeling smell, not a contract.",
    tags: ["domain-modeling", "api-data", "staff-judgment"],
    source: technicalSources.domainModeling,
  },
  {
    id: "shared-attio-intent-shaped-api",
    skillId: "api-data",
    track: "engineering",
    type: "choice",
    eyebrow: "API contracts",
    prompt: "A user copies a rule and its related records into another organization. Which API shape most clearly expresses the domain operation?",
    instruction: "Choose the best contract for the operation.",
    options: [
      { id: "copy", label: "POST /rules/:id/copy with an explicit target" },
      { id: "row-patch", label: "PATCH /table-row/:id and let the client assemble the copy" },
      { id: "generic", label: "POST /commands with an untyped JSON payload" },
      { id: "client", label: "No API operation; duplicate rows entirely in the browser" },
    ],
    correctOptionId: "copy",
    explanation: "An action endpoint can make authorization, validation, identity mapping and failure semantics explicit. Mirroring tables or pushing the operation into a client hides the invariant boundary.",
    tags: ["api-data", "domain-modeling", "staff-judgment"],
    source: technicalSources.apiDesign,
  },
  {
    id: "shared-attio-retry-safe-write",
    skillId: "api-data",
    track: "engineering",
    type: "multi-select",
    eyebrow: "API contracts",
    prompt: "A client times out while creating a potentially expensive copy operation. Which measures make a retry safe and diagnosable?",
    instruction: "Select every sound measure.",
    options: [
      { id: "key", label: "Persist an idempotency key with the operation result" },
      { id: "payload", label: "Reject reuse of a key with a different payload" },
      { id: "backoff", label: "Use bounded exponential backoff with jitter" },
      { id: "timeout", label: "Treat the timeout as proof the server did nothing" },
      { id: "stack", label: "Return raw server stack traces to explain failures" },
    ],
    correctOptionIds: ["key", "payload", "backoff"],
    explanation: "A timeout only says the caller stopped waiting; the server may have committed. Idempotency-key scope and payload consistency protect retries, while bounded backoff avoids synchronized retry storms. Error responses should be actionable without leaking internals.",
    tags: ["api-data", "transactions", "distributed-systems"],
    source: technicalSources.apiDesign,
  },
  {
    id: "shared-attio-lost-update",
    skillId: "transactions",
    track: "engineering",
    type: "choice",
    eyebrow: "Transactions & concurrency",
    prompt: "Two editors read version 7 of a record and both save changes. What is the simplest robust protection against one silently overwriting the other?",
    instruction: "Choose the strongest default for an infrequent-conflict product workflow.",
    options: [
      { id: "optimistic", label: "Update with WHERE id = ? AND version = 7, then detect zero rows" },
      { id: "last-write", label: "Accept last-write-wins and hide the conflict" },
      { id: "read-committed", label: "Rely on PostgreSQL Read Committed alone" },
      { id: "global-lock", label: "Lock every record in the organization forever" },
    ],
    correctOptionId: "optimistic",
    explanation: "An expected-version predicate turns a silent lost update into an explicit conflict the service can resolve. Read Committed does not prevent this race, and a global lock is disproportionate.",
    tags: ["transactions", "api-data", "domain-modeling"],
    source: technicalSources.postgres,
  },
  {
    id: "shared-attio-graph-copy-order",
    skillId: "transactions",
    track: "engineering",
    type: "ordering",
    eyebrow: "Transactions & data modeling",
    prompt: "For a bounded graph-copy operation, order the design work before inserting target records.",
    instruction: "Arrange the steps from semantic definition to durable write.",
    items: [
      { id: "scope", label: "Define which relations are copied and which remain shared" },
      { id: "authorize", label: "Authorize source/target and validate target capabilities" },
      { id: "map", label: "Build the old-identity to new-identity mapping" },
      { id: "stage", label: "Insert in dependency order inside the durable transaction" },
    ],
    correctOrder: ["scope", "authorize", "map", "stage"],
    explanation: "Graph copying is primarily a domain-identity problem. Scope and permissions determine what is legal; the identity map prevents mixed references; only then should bounded writes be staged atomically.",
    tags: ["transactions", "domain-modeling", "api-data", "staff-judgment"],
    source: technicalSources.postgres,
  },
];

export const attioExerciseModule = defineCompanyExercises("attio", [
  {
    id: "attio-why-spine",
    companyId: "attio",
    skillId: "company-motivation",
    track: "interview",
    type: "ordering",
    eyebrow: "Why Attio",
    prompt: "Reconstruct a concise, evidence-backed Why Attio answer.",
    instruction: "Order the beats from company hook to close.",
    items: [
      { id: "hook", label: "Flexible data model and hands-on Staff scope are the specific hook" },
      { id: "proof", label: "Connect that hook to typed capabilities, i18n and resource-planning foundations" },
      { id: "impact", label: "Explain the desired balance: Staff leverage while staying close to product" },
      { id: "close", label: "Close on domain modeling itself being a product problem" },
    ],
    correctOrder: ["hook", "proof", "impact", "close"],
    explanation: "The answer starts with Attio's product and role, earns credibility with concrete cross-layer proof, states the desired working model, and ends with a memorable product-specific thesis.",
    tags: ["company-motivation", "career-narrative", "staff-judgment"],
    answerExamples: [
      {
        id: "spoken",
        label: "30–60 second answer",
        answer: "Attio is interesting to me because the product itself is built around a flexible data model, and the Staff role appears to combine deep product work with architectural judgment. That maps strongly to work I’ve done around typed capabilities, internationalization and resource-planning foundations—problems where the hard part was getting the domain model and product behavior right across layers, not just implementing a screen. I’ve also repeatedly had to turn broad product intent into detailed requirements or interaction designs and refine them through strong product/design feedback. I also like roles where Staff impact still includes shipping product directly, which is the balance I’m looking for next.",
        source: companySources.attio,
      },
    ],
    source: companySources.attio,
  },
  {
    id: "attio-proof-selection",
    companyId: "attio",
    skillId: "company-motivation",
    track: "interview",
    type: "multi-select",
    eyebrow: "Why Attio",
    prompt: "Which proof points best support the claim that Attio's flexible model and Staff product scope fit your background?",
    instruction: "Select the strongest evidence anchors.",
    options: [
      { id: "capabilities", label: "Typed capabilities and internationalization across storage, backend and frontend" },
      { id: "resource-grid", label: "Appfire resource-planning architecture that enabled grouping/filtering" },
      { id: "mentoring", label: "Mentoring another engineer into meaningful ownership" },
      { id: "generic", label: "I have always liked CRM products" },
      { id: "overclaim", label: "I have operated large distributed systems at global scale" },
    ],
    correctOptionIds: ["capabilities", "resource-grid", "mentoring"],
    explanation: "The first three are concrete, defensible evidence for cross-layer modeling, architectural judgment and people leverage. Generic enthusiasm and unproven distributed-systems claims weaken the answer.",
    tags: ["company-motivation", "career-narrative", "claim-boundaries"],
    answerExamples: [
      {
        id: "proof-map",
        label: "Proof map",
        answer: "Primary: typed capabilities → internationalization. Architecture: Appfire grid/grouping. People leverage: mentoring. Keep backend examples in reserve and do not present distributed-systems depth as stronger than it is.",
        source: companySources.attio,
      },
    ],
    source: companySources.attio,
  },
  {
    id: "attio-boundary-probe",
    companyId: "attio",
    skillId: "claim-boundaries",
    track: "interview",
    type: "choice",
    eyebrow: "Defensible boundary",
    prompt: "An interviewer probes your distributed-systems depth after your domain-modeling answer. Which response is strongest?",
    instruction: "Choose the answer that is candid while still useful.",
    options: [
      { id: "bounded", label: "Say it is a growth area, then reason concretely from idempotency, transaction scope and retry semantics you have studied and applied" },
      { id: "inflate", label: "Claim deep production expertise so the conversation moves on" },
      { id: "deflect", label: "Say distributed systems are irrelevant to product engineering" },
      { id: "apology", label: "Apologize and stop discussing the technical trade-off" },
    ],
    correctOptionId: "bounded",
    explanation: "The answer card explicitly treats distributed-systems depth as a growth area. A strong Staff response states the boundary, then demonstrates precise reasoning and concrete adjacent experience without overclaiming.",
    tags: ["claim-boundaries", "staff-judgment", "distributed-systems"],
    answerExamples: [
      {
        id: "boundary",
        label: "Defensible response",
        answer: "Distributed systems depth is a growth area for me, so I would not present myself as a specialist. I can still reason about the relevant boundaries: idempotent commands for ambiguous retries, transaction scope around durable invariants, and explicit handling for conflicts or serialization failures. My strongest evidence is cross-layer product delivery; I would be clear about where I am extending that experience.",
        source: companySources.attio,
      },
    ],
    source: companySources.attio,
  },
]);
