import type { Exercise, Skill } from "./domain";

const distributedSystemsSource = {
  title: "Distributed Systems & Async Work — Study Guide",
  url: "https://app.notion.com/p/3e0e60f718a9813facc4f533f2cf1803",
};

const nodeSource = {
  title: "Node.js & Backend Runtime — Study Guide",
  url: "https://app.notion.com/p/3e0e60f718a9812a9c13d798c63b454a",
};

const systemDesignSource = {
  title: "System Design — Study Guide",
  url: "https://app.notion.com/p/3e0e60f718a9814fbceec83ebd05676c",
};

const answerBankSource = {
  title: "Interview Answer Bank",
  url: "https://app.notion.com/p/3e0e60f718a981379164c3fbc583a94b",
};

const storyBankSource = {
  title: "Kalepa — Staff Story Bank",
  url: "https://app.notion.com/p/3dde60f718a981cea77feae7ee8acd4d",
};

export const skills: Skill[] = [
  { id: "distributed-systems", name: "Distributed systems", track: "engineering" },
  { id: "node-runtime", name: "Node.js runtime", track: "engineering" },
  { id: "system-design", name: "System design", track: "engineering" },
  { id: "career-narrative", name: "Career narrative", track: "interview" },
  { id: "company-motivation", name: "Company motivation", track: "interview" },
  { id: "claim-boundaries", name: "Claim boundaries", track: "interview" },
  { id: "behavioral", name: "Behavioral stories", track: "interview" },
];

export const exercises: Exercise[] = [
  {
    id: "ds-ack-window",
    skillId: "distributed-systems",
    track: "engineering",
    type: "choice",
    eyebrow: "Failure timeline",
    prompt:
      "A queue worker commits a database change, then crashes before acknowledging the message. What should you expect?",
    instruction: "Choose the strongest answer.",
    options: [
      { id: "lost", label: "The database automatically rolls the change back" },
      { id: "duplicate", label: "The message may be redelivered, so processing must tolerate duplicates" },
      { id: "exact", label: "The broker guarantees the side effect happened exactly once" },
      { id: "lock", label: "A longer queue visibility timeout fully prevents the problem" },
    ],
    correctOptionId: "duplicate",
    explanation:
      "The dangerous window is between committing the side effect and acknowledging the message. At-least-once delivery can replay the work, so durable idempotency or deduplication must protect the business outcome.",
    source: distributedSystemsSource,
  },
  {
    id: "ds-retry-design",
    skillId: "distributed-systems",
    track: "engineering",
    type: "multi-select",
    eyebrow: "Retry judgment",
    prompt: "Which controls belong in a responsible retry policy?",
    instruction: "Select every control that belongs.",
    options: [
      { id: "classify", label: "Classify transient and permanent failures" },
      { id: "jitter", label: "Use exponential backoff with jitter" },
      { id: "budget", label: "Set a maximum attempt or time budget" },
      { id: "forever", label: "Retry every failure forever" },
      { id: "replay", label: "Confirm the operation is safe to replay" },
    ],
    correctOptionIds: ["classify", "jitter", "budget", "replay"],
    explanation:
      "Retries are for potentially transient failures and replay-safe operations. Backoff, jitter and a bounded budget prevent a struggling dependency from turning into a retry storm.",
    source: distributedSystemsSource,
  },
  {
    id: "ds-exactly-once",
    skillId: "distributed-systems",
    track: "engineering",
    type: "choice",
    eyebrow: "Delivery semantics",
    prompt: "What is usually the more useful end-to-end target than claiming exactly-once delivery?",
    instruction: "Choose one answer.",
    options: [
      { id: "most-once", label: "At-most-once delivery and no retry path" },
      { id: "idempotent", label: "At-least-once delivery with idempotent processing and durable deduplication" },
      { id: "global-lock", label: "A single global distributed lock" },
      { id: "memory", label: "An in-memory set of processed message IDs" },
    ],
    correctOptionId: "idempotent",
    explanation:
      "A broker guarantee covers only its own boundary. Business side effects often cross databases and external services, so duplicate-tolerant processing and durable transactional boundaries matter more.",
    source: distributedSystemsSource,
  },
  {
    id: "node-production-debug",
    skillId: "node-runtime",
    track: "engineering",
    type: "multi-select",
    eyebrow: "Production debugging",
    prompt:
      "Node memory climbs under load and restarts temporarily help. Which signals are useful before guessing at a cause?",
    instruction: "Select the useful investigation signals.",
    options: [
      { id: "heap", label: "Heap/RSS trend and heap snapshots" },
      { id: "handles", label: "Active handles, listeners and cache sizes" },
      { id: "buffers", label: "Stream buffering and downstream socket counts" },
      { id: "rewrite", label: "Immediately rewrite the service in another runtime" },
      { id: "correlate", label: "Correlation with features, traffic and request concurrency" },
    ],
    correctOptionIds: ["heap", "handles", "buffers", "correlate"],
    explanation:
      "Rising memory is a symptom, not a diagnosis. Inspect heap and RSS separately, retained handles and listeners, buffers, caches and workload correlation before choosing a remediation.",
    source: nodeSource,
  },
  {
    id: "node-graceful-shutdown",
    skillId: "node-runtime",
    track: "engineering",
    type: "ordering",
    eyebrow: "Runtime lifecycle",
    prompt: "Put a graceful service shutdown into a sensible order.",
    instruction: "Use the arrows to arrange the lifecycle.",
    items: [
      { id: "close", label: "Close database and network resources" },
      { id: "stop-new", label: "Stop accepting new requests and jobs" },
      { id: "exit", label: "Exit the process" },
      { id: "drain", label: "Let in-flight work finish within a deadline" },
    ],
    correctOrder: ["stop-new", "drain", "close", "exit"],
    explanation:
      "First stop taking new work, then drain or safely abandon in-flight operations within a deadline, close resources, and finally exit. A sudden stop can create ambiguous or duplicate work.",
    source: nodeSource,
  },
  {
    id: "system-design-conversation",
    skillId: "system-design",
    track: "engineering",
    type: "ordering",
    eyebrow: "Design interview",
    prompt: "Reconstruct the opening arc of a Staff-level system-design conversation.",
    instruction: "Arrange the steps from first to last.",
    items: [
      { id: "simple", label: "Propose the simplest viable architecture" },
      { id: "requirements", label: "Clarify users, use cases and non-goals" },
      { id: "tradeoffs", label: "Add failures, scale and explicit trade-offs" },
      { id: "data", label: "Define core data and ownership" },
      { id: "scale", label: "Establish scale and constraints" },
    ],
    correctOrder: ["requirements", "scale", "data", "simple", "tradeoffs"],
    explanation:
      "Lead from the problem to a coherent simple design. Scale and reliability should refine an understood system, not replace requirements with premature component naming.",
    source: systemDesignSource,
  },
  {
    id: "narrative-introduction",
    skillId: "career-narrative",
    track: "interview",
    type: "anchor-reconstruction",
    eyebrow: "90-second introduction",
    prompt: "Build a concise introduction from structural anchors.",
    instruction: "Tap anchors in the order you would speak them. Leave distractors unused.",
    anchors: [
      { id: "identity", label: "Who I am professionally now" },
      { id: "history", label: "Relevant depth and progression" },
      { id: "proof", label: "One or two distinctive proof points" },
      { id: "direction", label: "What I am looking for next" },
      { id: "chronology", label: "A year-by-year career chronology" },
      { id: "every-tool", label: "A complete technology inventory" },
    ],
    correctOrder: ["identity", "history", "proof", "direction"],
    explanation:
      "A strong introduction gives the listener an identity, relevant progression, concrete differentiation and a clear direction. Detailed chronology and tool inventories dilute the signal.",
    source: answerBankSource,
  },
  {
    id: "narrative-why-company",
    skillId: "company-motivation",
    track: "interview",
    type: "anchor-reconstruction",
    eyebrow: "Company motivation",
    prompt: "Rebuild the default 30–60 second “Why this company?” answer.",
    instruction: "Choose only the essential anchors, in order.",
    anchors: [
      { id: "them", label: "Them: specific product or operating-model signal" },
      { id: "me", label: "Me: direct evidence of fit" },
      { id: "timing", label: "Timing: why the match matters now" },
      { id: "scorecard", label: "Recite the entire internal company scorecard" },
      { id: "generic", label: "Add generic praise that fits any startup" },
    ],
    correctOrder: ["them", "me", "timing"],
    explanation:
      "The canonical structure is them → me → timing. Specific evidence makes the answer credible; the internal ranking is supporting context, not the answer itself.",
    source: answerBankSource,
  },
  {
    id: "narrative-growth-area",
    skillId: "claim-boundaries",
    track: "interview",
    type: "choice",
    eyebrow: "Claim boundary",
    prompt: "Which description of distributed-systems experience is both strong and defensible?",
    instruction: "Choose the best phrasing.",
    options: [
      { id: "expert", label: "It is an established specialty proven across many large-scale systems" },
      { id: "avoid", label: "It is outside my profile, so I would avoid discussing it" },
      { id: "development", label: "It is a deliberate development area backed by growing mental models and honest boundaries" },
      { id: "vocabulary", label: "I know the terminology, which is equivalent to production depth" },
    ],
    correctOptionId: "development",
    explanation:
      "The preparation material explicitly treats distributed systems as a high-priority development area, not claimed expertise. Strong reasoning and precise boundaries are more credible than inflated positioning.",
    source: answerBankSource,
  },
  {
    id: "narrative-company-ranking",
    skillId: "company-motivation",
    track: "interview",
    type: "multi-select",
    eyebrow: "Search narrative",
    prompt: "Which ideas belong in a concise explanation of how you rank companies?",
    instruction: "Select the anchors worth retaining.",
    options: [
      { id: "floor", label: "A hard economic sustainability floor" },
      { id: "multi", label: "A multidimensional judgment above that floor" },
      { id: "unknowns", label: "Unknowns are things to verify, not automatic negatives" },
      { id: "evidence", label: "The ranking changes when evidence changes" },
      { id: "ai", label: "AI chooses the company and produces the final score" },
    ],
    correctOptionIds: ["floor", "multi", "unknowns", "evidence"],
    explanation:
      "The model is a hard floor followed by qualitative, evidence-driven comparison. AI can assist research, but the criteria and decision remain human-owned.",
    source: answerBankSource,
  },
  {
    id: "behavioral-failure",
    skillId: "behavioral",
    track: "interview",
    type: "ordering",
    eyebrow: "Failure story",
    prompt: "Arrange a direct, accountable failure answer.",
    instruction: "Put the story beats in speaking order.",
    items: [
      { id: "prevention", label: "Explain the concrete prevention or changed behavior" },
      { id: "context", label: "Give only enough context to understand the stakes" },
      { id: "ownership", label: "State what I personally got wrong" },
      { id: "correction", label: "Describe detection and correction, crediting others precisely" },
    ],
    correctOrder: ["context", "ownership", "correction", "prevention"],
    explanation:
      "The useful arc is context → personal ownership → correction → prevention. It should not hide accountability inside a team story or claim another engineer’s diagnosis as your own.",
    source: answerBankSource,
  },
  {
    id: "narrative-staff-case",
    skillId: "career-narrative",
    track: "interview",
    type: "anchor-reconstruction",
    eyebrow: "Staff positioning",
    prompt: "Reconstruct the evidence categories behind the Staff-level case.",
    instruction: "Select the four evidence anchors. Their order should form a natural argument.",
    anchors: [
      { id: "delivery", label: "Sustained hands-on delivery" },
      { id: "architecture", label: "Architectural direction" },
      { id: "boundaries", label: "Cross-boundary ownership" },
      { id: "leverage", label: "Making other engineers more effective" },
      { id: "title", label: "The title alone proves the scope" },
      { id: "everything", label: "Company-wide impact on every project" },
    ],
    correctOrder: ["delivery", "architecture", "boundaries", "leverage"],
    explanation:
      "The Staff case is the sustained combination of delivery, architecture, ownership across layers and leverage—not a title or an exaggerated claim that every project had organization-wide scope.",
    source: answerBankSource,
  },
  {
    id: "ds-poison-message",
    skillId: "distributed-systems",
    track: "engineering",
    type: "choice",
    eyebrow: "Failure containment",
    prompt: "A job fails deterministically on every attempt. What is the strongest next step after its retry budget is exhausted?",
    instruction: "Choose the responsible recovery path.",
    options: [
      { id: "forever", label: "Keep retrying so the job can never be lost" },
      { id: "drop", label: "Delete the job silently to protect throughput" },
      {
        id: "failed",
        label: "Move it to a failed or dead-letter state with context, ownership and a replay path",
      },
      { id: "restart", label: "Restart every worker and reset its attempt count" },
    ],
    correctOptionId: "failed",
    explanation:
      "Bounded retries stop a poison message from consuming capacity forever. A failed or dead-letter state should preserve enough context to diagnose safely, make ownership visible and support deliberate recovery or replay.",
    source: distributedSystemsSource,
  },
  {
    id: "ds-transactional-outbox",
    skillId: "distributed-systems",
    track: "engineering",
    type: "ordering",
    eyebrow: "Transactional boundary",
    prompt: "Put the transactional-outbox flow in order.",
    instruction: "Arrange the steps from the initiating transaction to consumption.",
    items: [
      { id: "consume", label: "A duplicate-tolerant consumer handles the event" },
      { id: "transaction", label: "Commit the domain change and an outbox row in one database transaction" },
      { id: "publish", label: "A separate publisher reads the outbox row and publishes the event" },
      { id: "mark", label: "Mark or remove the outbox record after publishing" },
    ],
    correctOrder: ["transaction", "publish", "mark", "consume"],
    explanation:
      "The shared database transaction makes the domain change and intent-to-publish atomic. Publishing remains asynchronous and may repeat, so consumers still need duplicate-tolerant processing.",
    source: distributedSystemsSource,
  },
  {
    id: "ds-stale-event",
    skillId: "distributed-systems",
    track: "engineering",
    type: "choice",
    eyebrow: "Event ordering",
    prompt: "An entity is already at version 41 when an event for version 39 arrives. What is the safest default response?",
    instruction: "Choose one answer.",
    options: [
      { id: "apply", label: "Apply version 39 because every event must mutate state" },
      { id: "ignore", label: "Ignore the stale event and retain version 41" },
      { id: "reset", label: "Reset the entity to version 39 and replay from there" },
      { id: "global", label: "Introduce global ordering for every entity" },
    ],
    correctOptionId: "ignore",
    explanation:
      "Sequence numbers or entity versions make stale events detectable. Per-entity ordering or reconciliation is often enough; imposing global ordering is expensive and usually unnecessary.",
    source: distributedSystemsSource,
  },
  {
    id: "ds-overload-controls",
    skillId: "distributed-systems",
    track: "engineering",
    type: "multi-select",
    eyebrow: "Backpressure",
    prompt: "A worker system receives work faster than it can process it. Which controls reduce overload rather than amplify it?",
    instruction: "Select every useful control.",
    options: [
      { id: "bounded", label: "Bound queues and worker concurrency" },
      { id: "limits", label: "Apply rate limits or per-tenant quotas" },
      { id: "shed", label: "Shed or reject low-priority work early" },
      { id: "priority", label: "Prioritize important work" },
      { id: "retries", label: "Increase immediate retries for every failure" },
      { id: "depth", label: "Watch queue depth but ignore queue age" },
    ],
    correctOptionIds: ["bounded", "limits", "shed", "priority"],
    explanation:
      "Admission control, bounded concurrency, prioritization and load shedding keep demand aligned with capacity. Immediate retries add pressure, while queue age often reveals user-visible delay better than depth alone.",
    source: distributedSystemsSource,
  },
  {
    id: "node-cpu-work",
    skillId: "node-runtime",
    track: "engineering",
    type: "choice",
    eyebrow: "Event-loop pressure",
    prompt: "Why can one CPU-heavy JavaScript request slow unrelated requests in the same Node process?",
    instruction: "Choose the practical runtime explanation.",
    options: [
      { id: "network", label: "Network I/O always runs on the JavaScript thread" },
      { id: "loop", label: "Long-running JavaScript blocks progress on the shared event loop" },
      { id: "database", label: "Every request opens a new database connection" },
      { id: "promise", label: "Promises execute each callback in a new process" },
    ],
    correctOptionId: "loop",
    explanation:
      "Node can delegate much I/O, but JavaScript callbacks still need the event loop. CPU-heavy synchronous work monopolizes it, delaying otherwise unrelated request progress.",
    source: nodeSource,
  },
  {
    id: "node-cancellation",
    skillId: "node-runtime",
    track: "engineering",
    type: "multi-select",
    eyebrow: "Request cancellation",
    prompt: "A client disconnects while an expensive handler is still calling dependencies. Which questions belong in the design?",
    instruction: "Select every relevant question.",
    options: [
      { id: "db", label: "Can the active database query be cancelled?" },
      { id: "abort", label: "Should downstream HTTP calls receive an abort signal?" },
      { id: "continue", label: "Is the operation safe and useful to continue without the caller?" },
      { id: "discover", label: "If it completes, how can the client discover the outcome?" },
      { id: "automatic", label: "Does disconnecting automatically roll back every downstream side effect?" },
    ],
    correctOptionIds: ["db", "abort", "continue", "discover"],
    explanation:
      "Caller cancellation does not automatically cancel dependency work or undo committed effects. Propagation, safe continuation and outcome discovery are correctness decisions, not merely optimizations.",
    source: nodeSource,
  },
  {
    id: "node-bounded-concurrency",
    skillId: "node-runtime",
    track: "engineering",
    type: "choice",
    eyebrow: "Concurrency control",
    prompt: "A handler runs Promise.all over 20,000 records and exhausts downstream connections. What is the best first redesign?",
    instruction: "Choose one answer.",
    options: [
      { id: "more", label: "Raise every connection limit until all 20,000 calls run together" },
      { id: "bounded", label: "Process with bounded concurrency aligned to downstream capacity" },
      { id: "sync", label: "Replace every asynchronous call with synchronous I/O" },
      { id: "ignore", label: "Ignore the connection errors and let Promise.all retry itself" },
    ],
    correctOptionId: "bounded",
    explanation:
      "Unbounded Promise.all can create thousands of simultaneous requests. A concurrency limit protects the dependency and often improves effective throughput by avoiding saturation and queueing collapse.",
    source: nodeSource,
  },
  {
    id: "system-design-scale-first",
    skillId: "system-design",
    track: "engineering",
    type: "choice",
    eyebrow: "Scale judgment",
    prompt: "An estimate suggests roughly 580 writes per second on average, with a 5–10× peak. What is the strongest starting position?",
    instruction: "Choose the most defensible design judgment.",
    options: [
      { id: "shard", label: "Shard immediately because the product has millions of users" },
      { id: "relational", label: "Start with a relational database and evolve when measured bottlenecks justify it" },
      { id: "microservices", label: "Create one microservice per entity before defining invariants" },
      { id: "cache", label: "Treat a cache as the authoritative write store" },
    ],
    correctOptionId: "relational",
    explanation:
      "Order-of-magnitude estimates should guide architecture, not trigger fashionable complexity. This load may fit a carefully designed relational system; sharding should answer a demonstrated bottleneck.",
    source: systemDesignSource,
  },
  {
    id: "system-design-cache-policy",
    skillId: "system-design",
    track: "engineering",
    type: "multi-select",
    eyebrow: "Cache design",
    prompt: "Before adding a read cache, which decisions should be explicit?",
    instruction: "Select every decision that belongs.",
    options: [
      { id: "authority", label: "The authoritative source of the data" },
      { id: "staleness", label: "TTL and acceptable staleness" },
      { id: "invalidation", label: "Invalidation behavior" },
      { id: "scope", label: "Tenant or user scope in cache keys" },
      { id: "free", label: "Assume the cache creates no consistency or operational cost" },
    ],
    correctOptionIds: ["authority", "staleness", "invalidation", "scope"],
    explanation:
      "A cache is another copy of data. Its authority, keys, staleness, invalidation and isolation rules must be deliberate so a latency optimization does not become a correctness or security bug.",
    source: systemDesignSource,
  },
  {
    id: "system-design-realtime-recovery",
    skillId: "system-design",
    track: "engineering",
    type: "ordering",
    eyebrow: "Realtime recovery",
    prompt: "Arrange a robust snapshot-plus-events client flow.",
    instruction: "Put the lifecycle in order.",
    items: [
      { id: "events", label: "Apply authorized incremental events" },
      { id: "snapshot", label: "Fetch an authoritative snapshot" },
      { id: "uncertain", label: "Detect a reconnect, gap or uncertain event sequence" },
      { id: "reconcile", label: "Refetch and reconcile with authoritative state" },
    ],
    correctOrder: ["snapshot", "events", "uncertain", "reconcile"],
    explanation:
      "Realtime delivery can miss, duplicate or reorder events. Starting from a snapshot and refetching when continuity is uncertain keeps the server's authoritative state in control.",
    source: systemDesignSource,
  },
  {
    id: "narrative-strengths",
    skillId: "career-narrative",
    track: "interview",
    type: "multi-select",
    eyebrow: "Strengths answer",
    prompt: "Which anchors belong in the prepared answer about strongest areas?",
    instruction: "Select the four supported anchors.",
    options: [
      { id: "workflow", label: "Coherent technical models for complex workflows across layers" },
      { id: "frontend", label: "Frontend architecture and shared foundations" },
      { id: "leverage", label: "Foundations and mentoring that make others more effective" },
      { id: "ai", label: "AI-assisted engineering with human-owned judgment and verification" },
      { id: "specialist", label: "Established distributed-systems specialization" },
    ],
    correctOptionIds: ["workflow", "frontend", "leverage", "ai"],
    explanation:
      "The prepared strengths combine cross-layer product modeling, frontend depth, reusable and people leverage, and deliberate AI use. Distributed systems is explicitly framed as a development area, not an established specialty.",
    source: answerBankSource,
  },
  {
    id: "narrative-staff-boundary",
    skillId: "career-narrative",
    track: "interview",
    type: "choice",
    eyebrow: "Staff case",
    prompt: "Which closing line makes the Staff-level case strong without overstating it?",
    instruction: "Choose the most credible boundary.",
    options: [
      { id: "title", label: "My title proves that every project had company-wide scope" },
      { id: "code", label: "I qualify because I produce more code than other engineers" },
      {
        id: "combination",
        label: "The case is sustained hands-on delivery, architectural direction, cross-boundary ownership and leverage—not universal company-wide scope",
      },
      { id: "coordination", label: "Staff impact means leaving implementation entirely to others" },
    ],
    correctOptionId: "combination",
    explanation:
      "The answer bank grounds the Staff case in several forms of leverage while explicitly refusing the claim that every project had company-wide scope.",
    source: answerBankSource,
  },
  {
    id: "narrative-extended-why-company",
    skillId: "company-motivation",
    track: "interview",
    type: "ordering",
    eyebrow: "Extended motivation",
    prompt: "Reconstruct the extended “Why this company?” flow.",
    instruction: "Arrange the answer from context to conclusion.",
    items: [
      { id: "me", label: "Connect the role to direct evidence from my experience" },
      { id: "ranking", label: "Briefly establish the structured search and ranking context" },
      { id: "timing", label: "Explain why the match matters now" },
      { id: "them", label: "Name the decisive company-specific product or operating signal" },
    ],
    correctOrder: ["ranking", "them", "me", "timing"],
    explanation:
      "The extended form adds a short structured-search context before the core them → me → timing answer. The ranking establishes genuine interest but should not displace the company and fit.",
    source: answerBankSource,
  },
  {
    id: "narrative-ranking-context",
    skillId: "company-motivation",
    track: "interview",
    type: "choice",
    eyebrow: "Motivation emphasis",
    prompt: "How should the internal company ranking appear in a motivation answer?",
    instruction: "Choose the strongest use of it.",
    options: [
      { id: "whole", label: "Recite the full scorecard because the ranking is the answer" },
      { id: "proof", label: "Use it briefly as evidence of genuine interest, then focus on the company, fit and timing" },
      { id: "ai", label: "Say that AI selected the company objectively" },
      { id: "hide", label: "Never mention a structured search, even when asked how the company stood out" },
    ],
    correctOptionId: "proof",
    explanation:
      "Ranking context can show deliberate research, but it is supporting evidence. A persuasive answer spends most of its time on specific company signals, credible personal fit and why the opportunity matters now.",
    source: answerBankSource,
  },
  {
    id: "narrative-ai-boundaries",
    skillId: "claim-boundaries",
    track: "interview",
    type: "multi-select",
    eyebrow: "AI claim boundary",
    prompt: "Which points belong in the prepared answer about using AI in engineering?",
    instruction: "Select every defensible point.",
    options: [
      { id: "loop", label: "Use AI across understanding, design, implementation, debugging, tests and documentation" },
      { id: "context", label: "Keep durable context, bounded delegation and explicit sources of truth" },
      { id: "verify", label: "Independently review diffs, tests and runtime behavior" },
      { id: "ownership", label: "Keep product and architectural judgment human-owned" },
      { id: "metric", label: "Claim a measured productivity or defect-rate improvement without measurements" },
    ],
    correctOptionIds: ["loop", "context", "verify", "ownership"],
    explanation:
      "The prepared position is broad AI use inside a deliberately reliable workflow. It preserves human judgment and independent verification, and explicitly avoids unsupported productivity or quality metrics.",
    source: answerBankSource,
  },
  {
    id: "narrative-full-stack-boundary",
    skillId: "claim-boundaries",
    track: "interview",
    type: "choice",
    eyebrow: "Scope boundary",
    prompt: "Which answer best handles a challenge to the full-stack label?",
    instruction: "Choose the honest and evidence-backed framing.",
    options: [
      { id: "equal", label: "My depth is identical in every frontend and backend technology" },
      { id: "frontend", label: "I should avoid calling myself full-stack because frontend is my deepest area" },
      {
        id: "qualified",
        label: "Frontend architecture is my deepest historical area; the full-stack claim comes from real cross-layer scope, not equal depth everywhere",
      },
      { id: "recent", label: "A recent backend project makes my frontend history irrelevant" },
    ],
    correctOptionId: "qualified",
    explanation:
      "The answer bank preserves both truths: deep frontend history and substantial cross-stack ownership. It avoids pretending that experience is equally deep on every layer.",
    source: answerBankSource,
  },
  {
    id: "narrative-kalepa-exit",
    skillId: "claim-boundaries",
    track: "interview",
    type: "choice",
    eyebrow: "Direct probe",
    prompt: "An interviewer asks directly whether you resigned from Kalepa. What is the correct core response?",
    instruction: "Choose the precise answer.",
    options: [
      { id: "speculate", label: "No; then speculate about the company’s internal reasons" },
      { id: "ended", label: "No. Kalepa ended the contract." },
      { id: "avoid", label: "Redirect without answering the literal question" },
      { id: "mutual", label: "Describe it as a mutual decision to make it sound smoother" },
    ],
    correctOptionId: "ended",
    explanation:
      "The canonical answer is direct: the contract was ended by Kalepa. Follow-up can cover delivered work and learning, but should not invent or speculate about internal reasoning.",
    source: answerBankSource,
  },
  {
    id: "behavioral-docx-attribution",
    skillId: "behavioral",
    track: "interview",
    type: "choice",
    eyebrow: "Ownership precision",
    prompt: "Which version keeps attribution accurate in the DOCX workflow story?",
    instruction: "Choose the evidence-backed ownership statement.",
    options: [
      { id: "everything", label: "I solely owned the PDF editor, DOCX editor and all backend generation" },
      {
        id: "bounded",
        label: "I owned the Word editor, preview, packaging and multi-line variables; Krysia owned the PDF editor, and backend generation was co-owned",
      },
      { id: "backend", label: "I only worked on backend generation and did not own product-facing workflow pieces" },
      { id: "metric", label: "I can prove a numeric revenue impact from the workflow" },
    ],
    correctOptionId: "bounded",
    explanation:
      "The story bank explicitly separates ownership: Word-side workflow and packaging belonged to Maciej, the PDF editor to Krysia, and backend generation was shared with Maciek Piktel. No numeric revenue impact is established.",
    source: storyBankSource,
  },
  {
    id: "behavioral-failure-boundaries",
    skillId: "behavioral",
    track: "interview",
    type: "multi-select",
    eyebrow: "Failure ownership",
    prompt: "Which statements keep the Exposure Summary failure story accountable and accurate?",
    instruction: "Select every supported boundary.",
    options: [
      { id: "own", label: "Own the missing performance analysis and large-data testing" },
      { id: "credit", label: "Credit Rafał with the later performance diagnosis and remediation" },
      { id: "lesson", label: "Explain the changed definition of done around scale and failure modes" },
      { id: "incident", label: "Claim the endpoint caused a whole-platform incident" },
      { id: "diagnosis", label: "Claim detailed ownership of the diagnosis discovered later by someone else" },
    ],
    correctOptionIds: ["own", "credit", "lesson"],
    explanation:
      "The credible story owns the original implementation and missing validation, credits the later diagnosis and fixes correctly, and explains the changed practice. It does not inflate the incident or borrow another engineer’s analysis.",
    source: storyBankSource,
  },
  {
    id: "behavioral-grid-story",
    skillId: "behavioral",
    track: "interview",
    type: "anchor-reconstruction",
    eyebrow: "Architecture story",
    prompt: "Reconstruct the evidence-backed arc of the Appfire Resources-grid story.",
    instruction: "Choose the four supported anchors in a natural story order. Leave attribution traps unused.",
    anchors: [
      { id: "need", label: "A necessary but intimidating rewrite needed executable sequencing" },
      { id: "context", label: "Gather domain context from Robert and architectural coaching from Łukasz" },
      { id: "foundation", label: "Build the domain/application foundation before replacing the UI" },
      { id: "outcome", label: "Deliver the new UI and enable grouping and filtering on that foundation" },
      { id: "codesign", label: "Describe Robert and Łukasz as co-owners of the frontend architecture" },
      { id: "intern", label: "Attribute the new UI architecture to the intern who worked on the old UI" },
    ],
    correctOrder: ["need", "context", "foundation", "outcome"],
    explanation:
      "The story’s decision was how to stage a clearly necessary rewrite: learn the domain, establish the new foundation, then replace the UI and build previously impractical capabilities. Context and coaching should not be misrepresented as co-ownership.",
    source: storyBankSource,
  },
];

export function getSkill(skillId: string) {
  return skills.find((skill) => skill.id === skillId);
}
