import type { Exercise } from "../domain";

const source = {
  title: "Distributed Systems & Async Work — Study Guide",
  url: "https://app.notion.com/p/3e0e60f718a9813facc4f533f2cf1803",
};

/** Short, reusable drills that build from recognizing a failure to explaining its recovery. */
export const distributedSystemsPhaseThreeExercises: Exercise[] = [
  {
    id: "ds3-ambiguous-timeout",
    skillId: "distributed-systems",
    track: "engineering",
    type: "choice",
    evidenceLevel: "recognize",
    difficulty: 1,
    eyebrow: "Ambiguous outcome",
    prompt: "A client times out after asking a service to create a payment. What does the timeout tell you?",
    instruction: "Choose the conclusion you can safely draw.",
    options: [
      { id: "failed", label: "The service definitely did not create the payment" },
      { id: "committed", label: "The service definitely committed the payment" },
      { id: "unknown", label: "The outcome is unknown to the client; check or retry through a stable operation identity" },
      { id: "rollback", label: "The service automatically rolled back when the client stopped waiting" },
    ],
    correctOptionId: "unknown",
    explanation: "The request may have arrived and committed while its response was lost. A stable idempotency key or operation ID lets the client discover the result without creating a second payment.",
    tags: ["distributed-systems", "api-data"],
    source,
  },
  {
    id: "ds3-consistency-boundary",
    skillId: "distributed-systems",
    track: "engineering",
    type: "choice",
    evidenceLevel: "recognize",
    difficulty: 1,
    eyebrow: "Consistency judgment",
    prompt: "A product must prevent two confirmed reservations from consuming the same final unit. Its search index may lag briefly. Where should you coordinate strongly?",
    instruction: "Choose the boundary that protects the business invariant.",
    options: [
      { id: "index", label: "Make the search index perfectly current before accepting a reservation" },
      { id: "none", label: "Use eventual consistency for both paths and accept overselling silently" },
      { id: "global", label: "Serialize all reads and writes across the entire product" },
      { id: "reservation", label: "Protect the final-unit reservation in authoritative storage; let search catch up" },
    ],
    correctOptionId: "reservation",
    explanation: "Consistency follows the invariant. The authoritative reservation needs a concurrency guard such as a conditional update or transaction; a derived search index can converge later if the product tolerates its lag.",
    tags: ["distributed-systems", "transactions", "api-data"],
    source,
  },
  {
    id: "ds3-idempotent-create",
    skillId: "distributed-systems",
    track: "engineering",
    type: "ordering",
    evidenceLevel: "apply",
    difficulty: 2,
    eyebrow: "Concurrent retries",
    prompt: "Two requests with the same idempotency key arrive together for a create operation. Order the durable handling path.",
    instruction: "Arrange the steps into a safe sequence.",
    items: [
      { id: "return", label: "Return the saved outcome to either retry" },
      { id: "claim", label: "Claim the key using a uniqueness constraint inside the operation boundary" },
      { id: "validate", label: "Validate the request and derive an operation and payload fingerprint" },
      { id: "commit", label: "Commit the business change and its recorded outcome consistently" },
    ],
    correctOrder: ["validate", "claim", "commit", "return"],
    explanation: "A read-then-insert check alone races. Durable uniqueness chooses one owner; a conflicting request must match the saved operation and payload fingerprint before receiving its recorded outcome. Couple that result to the business change. Exact transaction details depend on the storage design.",
    tags: ["distributed-systems", "transactions", "api-data"],
    source,
  },
  {
    id: "ds3-failed-job-recovery",
    skillId: "distributed-systems",
    track: "engineering",
    type: "ordering",
    evidenceLevel: "apply",
    difficulty: 2,
    eyebrow: "Failure recovery",
    prompt: "A queued job repeatedly fails with a permanent validation error. Order the recovery response.",
    instruction: "Arrange the steps from failure classification to a controlled replay.",
    items: [
      { id: "replay", label: "Replay deliberately after the cause is fixed, preserving job identity" },
      { id: "record", label: "Move it to a terminal failed state with safe diagnostic context" },
      { id: "classify", label: "Classify the error as permanent and stop automatic retries" },
      { id: "owner", label: "Surface the failure to an owner who can repair or reject it" },
    ],
    correctOrder: ["classify", "record", "owner", "replay"],
    explanation: "A poison job should not consume capacity forever. Bounded retries and a durable failed state make the failure observable; an owned repair path makes later replay intentional and duplicate-safe.",
    tags: ["distributed-systems", "product-judgment"],
    source,
  },
  {
    id: "ds3-recall-outbox-gap",
    skillId: "distributed-systems",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "recall",
    difficulty: 2,
    eyebrow: "Say it first · outbox gap",
    prompt: "A service commits a database change, then crashes before publishing its event. Say aloud how a transactional outbox closes this gap.",
    instruction: "Recall the failure and mechanism before revealing the model points; then assess it honestly.",
    modelPoints: [
      "The database change can persist while the event is never published.",
      "Write the domain change and an outbox row in one database transaction; a separate publisher later sends the event.",
      "Publishing can still repeat, so consumers must tolerate duplicate events.",
    ],
    explanation: "The outbox makes the domain change and intent to publish atomic within one database. It does not guarantee a single end-to-end delivery.",
    tags: ["distributed-systems", "transactions"],
    source,
  },
  {
    id: "ds3-explain-queue-crash",
    skillId: "distributed-systems",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "explain",
    difficulty: 2,
    eyebrow: "Say it first · queue failure",
    prompt: "A worker commits its database update, then crashes before acknowledging the queue message. Explain aloud what can happen next and how you would protect the business outcome.",
    instruction: "Speak your answer before revealing the model points; then assess it honestly.",
    modelPoints: [
      "The broker may redeliver the message because it was never acknowledged, even though the database update committed.",
      "Use a durable operation or message identity and a uniqueness or transaction boundary so repeated processing has the same business outcome.",
      "A longer lease or visibility timeout can reduce overlap but cannot eliminate the commit-before-ack failure window.",
    ],
    explanation: "This is the central at-least-once delivery failure window. The useful guarantee is duplicate-tolerant business processing, not an unsupported exactly-once claim.",
    tags: ["distributed-systems", "transactions"],
    source,
  },
  {
    id: "ds3-explain-retry-budget",
    skillId: "distributed-systems",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "explain",
    difficulty: 2,
    eyebrow: "Say it first · retries",
    prompt: "A downstream service is slow and many workers time out together. Explain aloud a retry policy that helps recovery without causing a retry storm.",
    instruction: "Speak your answer before revealing the model points; then assess it honestly.",
    modelPoints: [
      "Retry only failures likely to be transient, after checking that the operation is safe to replay.",
      "Use exponential backoff with jitter so workers do not retry on the same schedule.",
      "Bound attempts or elapsed time, and put permanent failures into an owned failed or dead-letter path.",
      "Watch queue age and downstream health; limit concurrency or incoming work if backlog and latency grow.",
    ],
    explanation: "Retries are extra load on a struggling dependency. Classification, replay safety, jitter, a budget and overload signals make the policy defensible.",
    tags: ["distributed-systems", "performance"],
    source,
  },
  {
    id: "ds3-explain-progress-recovery",
    skillId: "distributed-systems",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "explain",
    difficulty: 3,
    eyebrow: "Say it first · async design",
    prompt: "Imagine moving a large synchronous graph-copy request to a background job. Explain aloud what the UI and operators need to see after a worker dies halfway through. Frame this as a proposed design.",
    instruction: "Speak your answer before revealing the model points; then assess it honestly.",
    modelPoints: [
      "Persist a job ID and state, attempt count, progress, result or failure details; return the ID so the UI can poll status.",
      "A lease expiry can let another worker reclaim the job, but resumed work needs stable job identity and duplicate-safe writes or checkpoints.",
      "Define cancellation and partial-result semantics rather than implying that a stopped worker rolls back external effects.",
      "Monitor backlog or queue age, terminal failures and recovery; expose a deliberate replay path.",
      "State clearly that this async architecture is a retrospective design exercise, not the shipped rule-copy implementation.",
    ],
    explanation: "A durable job record lets the user and operator distinguish slow, failed and completed work. Worker recovery must preserve the business invariant despite duplicate execution and partial failure.",
    tags: ["distributed-systems", "system-design", "product-judgment"],
    source,
  },
];
