import type { Exercise } from "../domain";
import { technicalSources } from "../sources";

const source = technicalSources.systemDesign;

// A short progression through requirements, architecture, data, and spoken trade-offs.
export const systemDesignDrillExercises: Exercise[] = [
  {
    id: "p3-system-design-requirements",
    skillId: "system-design",
    track: "engineering",
    type: "multi-select",
    evidenceLevel: "recognize",
    difficulty: 1,
    eyebrow: "Clarify the brief",
    prompt: "A team wants editable documents, previews, and generated downloads for several organizations. Which questions could change the first design?",
    instruction: "Select the questions that affect architecture or correctness.",
    options: [
      { id: "visual", label: "Which accent color should the download button use?" },
      { id: "duration", label: "How long can generation take, and must it continue after a client disconnects?" },
      { id: "version", label: "Must a generated file correspond to one exact document version?" },
      { id: "name", label: "What internal codename should the worker have?" },
      { id: "tenancy", label: "Who may edit, generate, and download across organization boundaries?" },
    ],
    correctOptionIds: ["duration", "version", "tenancy"],
    explanation: "Good opening questions expose latency, version identity, and authorization requirements. Those decisions affect whether work is asynchronous, what the artifact records, and how tenant access is enforced.",
    tags: ["system-design", "product-judgment", "domain-modeling"],
    source,
  },
  {
    id: "p3-system-design-generation-boundary",
    skillId: "system-design",
    track: "engineering",
    type: "choice",
    evidenceLevel: "recognize",
    difficulty: 2,
    eyebrow: "Choose a boundary",
    prompt: "Generation takes 10–60 seconds. Users need progress, and closing the tab should not cancel a requested download. Which starting design fits?",
    instruction: "Choose the strongest first design for these constraints.",
    options: [
      { id: "browser", label: "Keep generation in the browser and restart it if the tab closes." },
      { id: "sync", label: "Hold the HTTP request open until generation finishes; add a longer timeout." },
      { id: "job", label: "Create a generation job for an exact document version; return its ID and expose status while a worker produces the artifact." },
      { id: "services", label: "Split editing, preview, versioning, and generation into separate services before defining their data ownership." },
    ],
    correctOptionId: "job",
    explanation: "The duration and disconnect requirement justify a background job with durable identity and status. The cost is more job state and recovery logic, so keep the rest of the architecture simple until scale demands more.",
    tags: ["system-design", "api-data", "product-judgment"],
    source,
  },
  {
    id: "p3-system-design-search-tradeoff",
    skillId: "system-design",
    track: "engineering",
    type: "choice",
    evidenceLevel: "recognize",
    difficulty: 2,
    eyebrow: "Data ownership",
    prompt: "The document workflow now needs ranked full-text search. A few seconds of search lag is acceptable, but edits and permissions must be authoritative. What would you add first?",
    instruction: "Choose a design and consider its consistency cost.",
    options: [
      { id: "index-authority", label: "Move documents and permissions to a search index as their only source of truth." },
      { id: "search-derived", label: "Keep document and permission facts in the relational store; derive a search index and handle its lag explicitly." },
      { id: "all-cache", label: "Put every document in a shared cache with no tenant-scoped key or invalidation policy." },
      { id: "shard", label: "Shard the relational store immediately because full-text search has been requested." },
    ],
    correctOptionId: "search-derived",
    explanation: "A derived index fits ranked search while the relational store keeps authoritative versions and access rules. Search results may lag, so result visibility, reads, and downloads must honor current permissions.",
    tags: ["system-design", "api-data", "state-architecture"],
    source,
  },
  {
    id: "p3-system-design-opening-recall",
    skillId: "system-design",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "recall",
    difficulty: 1,
    eyebrow: "Recall the opening",
    prompt: "Before drawing boxes for the document workflow, recall the first four decisions in a system-design conversation.",
    instruction: "Say them aloud from memory in about 20 seconds, then reveal the checkpoints.",
    modelPoints: [
      "Clarify users, use cases, and non-goals.",
      "Estimate scale and name important constraints.",
      "Identify core data, invariants, and ownership.",
      "Sketch the simplest architecture that satisfies those requirements.",
    ],
    explanation: "A good recall answer follows the problem into its data and only then a simple architecture; the exact wording is unimportant.",
    tags: ["system-design", "staff-judgment"],
    source,
  },
  {
    id: "p3-system-design-explain-first-design",
    skillId: "system-design",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "explain",
    difficulty: 2,
    eyebrow: "Say the design",
    prompt: "Explain a first design for editable, versioned documents whose generation takes 10–60 seconds. Give one reason for each major boundary.",
    instruction: "Say it aloud in about 60 seconds, then reveal what a good answer covers.",
    modelPoints: [
      "Name the key requirements and one scale or latency assumption that would change the design.",
      "Keep document versions and permissions authoritative in a relational store; put generated files in object storage.",
      "Walk one flow: request generation for an exact version, create a durable job, run a worker, then expose status and the resulting artifact.",
      "State one trade-off or failure to validate next, such as retry behavior, queue age, or authorization at download time.",
    ],
    explanation: "A good answer connects requirements to ownership and a concrete flow, then names a cost or failure. There is room for different implementations if their guarantees and trade-offs are explicit.",
    tags: ["system-design", "domain-modeling", "staff-judgment"],
    source,
  },
  {
    id: "p3-system-design-generation-retry",
    skillId: "system-design",
    track: "engineering",
    type: "self-check",
    evidenceLevel: "explain",
    difficulty: 3,
    eyebrow: "Failure follow-up",
    prompt: "A worker writes a generated file, then times out before marking the job complete. The queue retries it. How should the design recover without showing two downloads?",
    instruction: "Explain the adjustment aloud in about 45 seconds, then self-check.",
    modelPoints: [
      "Keep a stable job identity tied to the requested document version so retrying does not create a new logical request.",
      "Make artifact publication and job completion safe to repeat or reconcile; expose one authoritative result for that job.",
      "Define how an ambiguous attempt is detected and recovered, and observe retries, stale jobs, and duplicate work.",
    ],
    explanation: "The important choice is the visible guarantee and recovery path after an ambiguous result. A retry may repeat computation, but it should converge on one job result; the exact storage mechanism can vary.",
    tags: ["system-design", "distributed-systems", "transactions"],
    source,
  },
];
